
USE `sql5680674`;

CREATE TABLE INFO(
    id INT PRIMARY KEY AUTO_INCREMENT,
    temperatura FLOAT DEFAULT NULL,
    humedad FLOAT DEFAULT NULL,
    movimiento INT DEFAULT NULL,
    tiempo DATE DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=3;



